// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WiseSpearComm.proto

package com.wispear.wisespear.comm;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqDeviceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 id = 1;
    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code tutorial.ReqDevice}
   */
  public static final class ReqDevice extends
      com.google.protobuf.GeneratedMessage
      implements ReqDeviceOrBuilder {
    // Use ReqDevice.newBuilder() to construct.
    private ReqDevice(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqDevice(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqDevice defaultInstance;
    public static ReqDevice getDefaultInstance() {
      return defaultInstance;
    }

    public ReqDevice getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wispear.wisespear.comm.Messages.internal_static_tutorial_ReqDevice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wispear.wisespear.comm.Messages.internal_static_tutorial_ReqDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wispear.wisespear.comm.Messages.ReqDevice.class, com.wispear.wisespear.comm.Messages.ReqDevice.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqDevice> PARSER =
        new com.google.protobuf.AbstractParser<ReqDevice>() {
      public ReqDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqDevice(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqDevice> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.ReqDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wispear.wisespear.comm.Messages.ReqDevice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ReqDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wispear.wisespear.comm.Messages.ReqDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_ReqDevice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_ReqDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wispear.wisespear.comm.Messages.ReqDevice.class, com.wispear.wisespear.comm.Messages.ReqDevice.Builder.class);
      }

      // Construct using com.wispear.wisespear.comm.Messages.ReqDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_ReqDevice_descriptor;
      }

      public com.wispear.wisespear.comm.Messages.ReqDevice getDefaultInstanceForType() {
        return com.wispear.wisespear.comm.Messages.ReqDevice.getDefaultInstance();
      }

      public com.wispear.wisespear.comm.Messages.ReqDevice build() {
        com.wispear.wisespear.comm.Messages.ReqDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wispear.wisespear.comm.Messages.ReqDevice buildPartial() {
        com.wispear.wisespear.comm.Messages.ReqDevice result = new com.wispear.wisespear.comm.Messages.ReqDevice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wispear.wisespear.comm.Messages.ReqDevice) {
          return mergeFrom((com.wispear.wisespear.comm.Messages.ReqDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wispear.wisespear.comm.Messages.ReqDevice other) {
        if (other == com.wispear.wisespear.comm.Messages.ReqDevice.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wispear.wisespear.comm.Messages.ReqDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wispear.wisespear.comm.Messages.ReqDevice) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 id = 1;
      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.ReqDevice)
    }

    static {
      defaultInstance = new ReqDevice(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.ReqDevice)
  }

  public interface DeviceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 id = 1;
    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    // required bytes mac_address = 2;
    /**
     * <code>required bytes mac_address = 2;</code>
     */
    boolean hasMacAddress();
    /**
     * <code>required bytes mac_address = 2;</code>
     */
    com.google.protobuf.ByteString getMacAddress();
  }
  /**
   * Protobuf type {@code tutorial.Device}
   */
  public static final class Device extends
      com.google.protobuf.GeneratedMessage
      implements DeviceOrBuilder {
    // Use Device.newBuilder() to construct.
    private Device(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Device(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Device defaultInstance;
    public static Device getDefaultInstance() {
      return defaultInstance;
    }

    public Device getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Device(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              macAddress_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wispear.wisespear.comm.Messages.internal_static_tutorial_Device_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wispear.wisespear.comm.Messages.internal_static_tutorial_Device_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wispear.wisespear.comm.Messages.Device.class, com.wispear.wisespear.comm.Messages.Device.Builder.class);
    }

    public static com.google.protobuf.Parser<Device> PARSER =
        new com.google.protobuf.AbstractParser<Device>() {
      public Device parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Device(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Device> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required bytes mac_address = 2;
    public static final int MAC_ADDRESS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString macAddress_;
    /**
     * <code>required bytes mac_address = 2;</code>
     */
    public boolean hasMacAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes mac_address = 2;</code>
     */
    public com.google.protobuf.ByteString getMacAddress() {
      return macAddress_;
    }

    private void initFields() {
      id_ = 0;
      macAddress_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMacAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, macAddress_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, macAddress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wispear.wisespear.comm.Messages.Device parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.Device parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wispear.wisespear.comm.Messages.Device prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Device}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wispear.wisespear.comm.Messages.DeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_Device_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_Device_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wispear.wisespear.comm.Messages.Device.class, com.wispear.wisespear.comm.Messages.Device.Builder.class);
      }

      // Construct using com.wispear.wisespear.comm.Messages.Device.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        macAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_Device_descriptor;
      }

      public com.wispear.wisespear.comm.Messages.Device getDefaultInstanceForType() {
        return com.wispear.wisespear.comm.Messages.Device.getDefaultInstance();
      }

      public com.wispear.wisespear.comm.Messages.Device build() {
        com.wispear.wisespear.comm.Messages.Device result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wispear.wisespear.comm.Messages.Device buildPartial() {
        com.wispear.wisespear.comm.Messages.Device result = new com.wispear.wisespear.comm.Messages.Device(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.macAddress_ = macAddress_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wispear.wisespear.comm.Messages.Device) {
          return mergeFrom((com.wispear.wisespear.comm.Messages.Device)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wispear.wisespear.comm.Messages.Device other) {
        if (other == com.wispear.wisespear.comm.Messages.Device.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMacAddress()) {
          setMacAddress(other.getMacAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasMacAddress()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wispear.wisespear.comm.Messages.Device parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wispear.wisespear.comm.Messages.Device) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 id = 1;
      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required bytes mac_address = 2;
      private com.google.protobuf.ByteString macAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mac_address = 2;</code>
       */
      public boolean hasMacAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes mac_address = 2;</code>
       */
      public com.google.protobuf.ByteString getMacAddress() {
        return macAddress_;
      }
      /**
       * <code>required bytes mac_address = 2;</code>
       */
      public Builder setMacAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        macAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mac_address = 2;</code>
       */
      public Builder clearMacAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        macAddress_ = getDefaultInstance().getMacAddress();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Device)
    }

    static {
      defaultInstance = new Device(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Device)
  }

  public interface AddDeviceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .tutorial.Device device = 1;
    /**
     * <code>required .tutorial.Device device = 1;</code>
     */
    boolean hasDevice();
    /**
     * <code>required .tutorial.Device device = 1;</code>
     */
    com.wispear.wisespear.comm.Messages.Device getDevice();
    /**
     * <code>required .tutorial.Device device = 1;</code>
     */
    com.wispear.wisespear.comm.Messages.DeviceOrBuilder getDeviceOrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.AddDevice}
   */
  public static final class AddDevice extends
      com.google.protobuf.GeneratedMessage
      implements AddDeviceOrBuilder {
    // Use AddDevice.newBuilder() to construct.
    private AddDevice(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddDevice(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddDevice defaultInstance;
    public static AddDevice getDefaultInstance() {
      return defaultInstance;
    }

    public AddDevice getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.wispear.wisespear.comm.Messages.Device.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = device_.toBuilder();
              }
              device_ = input.readMessage(com.wispear.wisespear.comm.Messages.Device.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(device_);
                device_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wispear.wisespear.comm.Messages.internal_static_tutorial_AddDevice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wispear.wisespear.comm.Messages.internal_static_tutorial_AddDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wispear.wisespear.comm.Messages.AddDevice.class, com.wispear.wisespear.comm.Messages.AddDevice.Builder.class);
    }

    public static com.google.protobuf.Parser<AddDevice> PARSER =
        new com.google.protobuf.AbstractParser<AddDevice>() {
      public AddDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddDevice(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddDevice> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .tutorial.Device device = 1;
    public static final int DEVICE_FIELD_NUMBER = 1;
    private com.wispear.wisespear.comm.Messages.Device device_;
    /**
     * <code>required .tutorial.Device device = 1;</code>
     */
    public boolean hasDevice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tutorial.Device device = 1;</code>
     */
    public com.wispear.wisespear.comm.Messages.Device getDevice() {
      return device_;
    }
    /**
     * <code>required .tutorial.Device device = 1;</code>
     */
    public com.wispear.wisespear.comm.Messages.DeviceOrBuilder getDeviceOrBuilder() {
      return device_;
    }

    private void initFields() {
      device_ = com.wispear.wisespear.comm.Messages.Device.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDevice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDevice().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, device_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, device_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wispear.wisespear.comm.Messages.AddDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wispear.wisespear.comm.Messages.AddDevice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.AddDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wispear.wisespear.comm.Messages.AddDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_AddDevice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_AddDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wispear.wisespear.comm.Messages.AddDevice.class, com.wispear.wisespear.comm.Messages.AddDevice.Builder.class);
      }

      // Construct using com.wispear.wisespear.comm.Messages.AddDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (deviceBuilder_ == null) {
          device_ = com.wispear.wisespear.comm.Messages.Device.getDefaultInstance();
        } else {
          deviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wispear.wisespear.comm.Messages.internal_static_tutorial_AddDevice_descriptor;
      }

      public com.wispear.wisespear.comm.Messages.AddDevice getDefaultInstanceForType() {
        return com.wispear.wisespear.comm.Messages.AddDevice.getDefaultInstance();
      }

      public com.wispear.wisespear.comm.Messages.AddDevice build() {
        com.wispear.wisespear.comm.Messages.AddDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wispear.wisespear.comm.Messages.AddDevice buildPartial() {
        com.wispear.wisespear.comm.Messages.AddDevice result = new com.wispear.wisespear.comm.Messages.AddDevice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (deviceBuilder_ == null) {
          result.device_ = device_;
        } else {
          result.device_ = deviceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wispear.wisespear.comm.Messages.AddDevice) {
          return mergeFrom((com.wispear.wisespear.comm.Messages.AddDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wispear.wisespear.comm.Messages.AddDevice other) {
        if (other == com.wispear.wisespear.comm.Messages.AddDevice.getDefaultInstance()) return this;
        if (other.hasDevice()) {
          mergeDevice(other.getDevice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDevice()) {
          
          return false;
        }
        if (!getDevice().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wispear.wisespear.comm.Messages.AddDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wispear.wisespear.comm.Messages.AddDevice) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .tutorial.Device device = 1;
      private com.wispear.wisespear.comm.Messages.Device device_ = com.wispear.wisespear.comm.Messages.Device.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wispear.wisespear.comm.Messages.Device, com.wispear.wisespear.comm.Messages.Device.Builder, com.wispear.wisespear.comm.Messages.DeviceOrBuilder> deviceBuilder_;
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public boolean hasDevice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public com.wispear.wisespear.comm.Messages.Device getDevice() {
        if (deviceBuilder_ == null) {
          return device_;
        } else {
          return deviceBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public Builder setDevice(com.wispear.wisespear.comm.Messages.Device value) {
        if (deviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          device_ = value;
          onChanged();
        } else {
          deviceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public Builder setDevice(
          com.wispear.wisespear.comm.Messages.Device.Builder builderForValue) {
        if (deviceBuilder_ == null) {
          device_ = builderForValue.build();
          onChanged();
        } else {
          deviceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public Builder mergeDevice(com.wispear.wisespear.comm.Messages.Device value) {
        if (deviceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              device_ != com.wispear.wisespear.comm.Messages.Device.getDefaultInstance()) {
            device_ =
              com.wispear.wisespear.comm.Messages.Device.newBuilder(device_).mergeFrom(value).buildPartial();
          } else {
            device_ = value;
          }
          onChanged();
        } else {
          deviceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public Builder clearDevice() {
        if (deviceBuilder_ == null) {
          device_ = com.wispear.wisespear.comm.Messages.Device.getDefaultInstance();
          onChanged();
        } else {
          deviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public com.wispear.wisespear.comm.Messages.Device.Builder getDeviceBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDeviceFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      public com.wispear.wisespear.comm.Messages.DeviceOrBuilder getDeviceOrBuilder() {
        if (deviceBuilder_ != null) {
          return deviceBuilder_.getMessageOrBuilder();
        } else {
          return device_;
        }
      }
      /**
       * <code>required .tutorial.Device device = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.wispear.wisespear.comm.Messages.Device, com.wispear.wisespear.comm.Messages.Device.Builder, com.wispear.wisespear.comm.Messages.DeviceOrBuilder> 
          getDeviceFieldBuilder() {
        if (deviceBuilder_ == null) {
          deviceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wispear.wisespear.comm.Messages.Device, com.wispear.wisespear.comm.Messages.Device.Builder, com.wispear.wisespear.comm.Messages.DeviceOrBuilder>(
                  device_,
                  getParentForChildren(),
                  isClean());
          device_ = null;
        }
        return deviceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.AddDevice)
    }

    static {
      defaultInstance = new AddDevice(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.AddDevice)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ReqDevice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ReqDevice_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Device_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Device_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddDevice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_AddDevice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WiseSpearComm.proto\022\010tutorial\"\027\n\tReqDe" +
      "vice\022\n\n\002id\030\001 \002(\r\")\n\006Device\022\n\n\002id\030\001 \002(\r\022\023" +
      "\n\013mac_address\030\002 \002(\014\"-\n\tAddDevice\022 \n\006devi" +
      "ce\030\001 \002(\0132\020.tutorial.DeviceB&\n\032com.wispea" +
      "r.wisespear.commB\010Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_ReqDevice_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_ReqDevice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_ReqDevice_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_tutorial_Device_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_Device_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Device_descriptor,
              new java.lang.String[] { "Id", "MacAddress", });
          internal_static_tutorial_AddDevice_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tutorial_AddDevice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_AddDevice_descriptor,
              new java.lang.String[] { "Device", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
